FROM caddy:2-alpine

COPY rootfs/ /

ENV API_ADDRESS app
ENV APP_ADDRESS app
ENV BROWSERSYNC_ADDRESS hot:3000
ENV BROWSERSYNC_UI_ADDRESS hot:3001
ENV MAIL_ADDRESS mail
ENV SITE_ADDRESS clevyr.run
ENV SOCKETIO_ADDRESS $APP_ADDRESS
ENV LOG_OUTPUT discard
