#!/bin/bash

# Any errors encountered will kill this script instead of being ignored.
set -e

echo 'Creating /etc/Caddyfile based on Caddyfile.template.' >&2

# Set default values
export \
    URL="${URL:-0.0.0.0:80}" \
    APP_PATH="${APP_PATH:-/var/www/html/public}" \
    TLS_OPTIONS="${TLS_OPTIONS:-off}" \
    APP_HOST="${APP_HOST:-app}" \
    APP_PORT="${APP_PORT:-9000}" \

export \
    SOCKET_HOST="${SOCKET_HOST:-$APP_HOST}" \
    SOCKET_PATH="${SOCKET_PATH:-/socket.io}" \
    SOCKET_PORT="${SOCKET_PORT:-6001}"

if [ "$SOCKET_PROXY" = "true" ]; then
    cat socket.template >> Caddyfile.template
    export \
        NOT="if {path} not_starts_with ${SOCKET_PATH}"
fi

cat fastcgi.template >> Caddyfile.template

envsubst '$URL $TLS_OPTIONS $APP_HOST $APP_PORT $APP_PATH $BASIC_AUTH_OPTIONS $SOCKET_PATH $SOCKET_HOST $SOCKET_PORT $NOT' < Caddyfile.template > /etc/Caddyfile

echo 'Starting Caddy.' >&2

exec caddy --conf /etc/Caddyfile --log stdout --agree="$ACME_AGREE"
